# Generated by Django 4.1 on 2022-09-22 12:47

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_userinformation_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='message',
        ),
        migrations.AddField(
            model_name='userinformation',
            name='user_email',
            field=models.CharField(default=builtins.print, max_length=100),
            preserve_default=False,
        ),
    ]
