# Generated by Django 4.1 on 2022-08-17 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_usercreatearticle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCreateArticle',
        ),
    ]
