# Generated by Django 4.1 on 2022-09-26 16:29

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_alter_articles_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='code',
            field=models.TextField(default=builtins.print),
            preserve_default=False,
        ),
    ]
