# Generated by Django 4.1 on 2022-10-01 18:34

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_remove_articles_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='code',
            field=models.TextField(default=builtins.print),
            preserve_default=False,
        ),
    ]
